/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolstuff.ibcsia;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;

/**
 *
 * @author bruhm
 */
public class StartScreen extends javax.swing.JFrame {

    /**
     * Creates new form StartScreen
     */
    public StartScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAddName = new javax.swing.JLabel();
        labelAddAddress = new javax.swing.JLabel();
        addAddressField = new javax.swing.JTextField();
        labelAddContact = new javax.swing.JLabel();
        addContactField = new javax.swing.JTextField();
        labelAddPest = new javax.swing.JLabel();
        addPestField = new javax.swing.JTextField();
        labelAddCost = new javax.swing.JLabel();
        addCostField = new javax.swing.JTextField();
        labelAddMemo = new javax.swing.JLabel();
        searchScreenBtn = new javax.swing.JButton();
        addNameField = new javax.swing.JTextField();
        tutorialBtn = new javax.swing.JButton();
        addClientBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        addMemoField = new javax.swing.JTextArea();
        labelAddLastName = new javax.swing.JLabel();
        addLastNameField = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelAddName.setText("Client First Name:");

        labelAddAddress.setText("Add Client Address Here:");

        addAddressField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addAddressFieldKeyPressed(evt);
            }
        });

        labelAddContact.setText("Add Client Contact Here:");

        addContactField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addContactFieldKeyPressed(evt);
            }
        });

        labelAddPest.setText("Add Pest Here:");

        addPestField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addPestFieldKeyPressed(evt);
            }
        });

        labelAddCost.setText("Add Cost Here:");

        addCostField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addCostFieldKeyPressed(evt);
            }
        });

        labelAddMemo.setText("Add Notes/Memos Here:");

        searchScreenBtn.setText("Search");
        searchScreenBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchScreenBtnMouseClicked(evt);
            }
        });

        addNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addNameFieldKeyPressed(evt);
            }
        });

        tutorialBtn.setText("Tutorial");
        tutorialBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tutorialBtnMouseClicked(evt);
            }
        });

        addClientBtn.setText("ADD CLIENT");
        addClientBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addClientBtnMouseClicked(evt);
            }
        });

        addMemoField.setColumns(20);
        addMemoField.setRows(5);
        addMemoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addMemoFieldKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(addMemoField);

        labelAddLastName.setText("Client Last Name:");

        addLastNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addLastNameFieldKeyPressed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(labelAddMemo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelAddCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelAddPest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelAddContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelAddAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(tutorialBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchScreenBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addAddressField)
                                    .addComponent(addContactField)
                                    .addComponent(addPestField)
                                    .addComponent(addCostField, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addClientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelAddName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelAddLastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addLastNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAddName)
                    .addComponent(addNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAddLastName)
                    .addComponent(addLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAddAddress)
                            .addComponent(addAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAddContact)
                            .addComponent(addContactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAddPest)
                            .addComponent(addPestField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAddCost))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(labelAddMemo)
                                .addGap(18, 18, 18)
                                .addComponent(searchScreenBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tutorialBtn)
                            .addComponent(addClientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(deleteBtn)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ArrayList<client> clientList = new ArrayList<client>();
    private void searchScreenBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchScreenBtnMouseClicked
        // TODO add your handling code here:
        SearchScreen x = new SearchScreen();
        x.setVisible(true);
    }//GEN-LAST:event_searchScreenBtnMouseClicked
    private String textFName;
    private void addNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addNameFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            textFName = addNameField.getText();
        }
    }//GEN-LAST:event_addNameFieldKeyPressed

    private void tutorialBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorialBtnMouseClicked
        // TODO add your handling code here:
        TutorialScreen y = new TutorialScreen();
        y.setVisible(true);
    }//GEN-LAST:event_tutorialBtnMouseClicked
    private String textAddress;
    private void addAddressFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addAddressFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            textAddress = addAddressField.getText();
        }
    }//GEN-LAST:event_addAddressFieldKeyPressed
    private String textContact;
    private void addContactFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addContactFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            textContact = addContactField.getText();
        }
    }//GEN-LAST:event_addContactFieldKeyPressed
    private String textPest;
    private void addPestFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addPestFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            textPest = addPestField.getText();
        }
    }//GEN-LAST:event_addPestFieldKeyPressed
    private double textCost;
    private void addCostFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addCostFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            textCost = Double.parseDouble(addCostField.getText());
        }
    }//GEN-LAST:event_addCostFieldKeyPressed
    private String textMemo;
    private void addMemoFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addMemoFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            textMemo = addMemoField.getText();
        }
    }//GEN-LAST:event_addMemoFieldKeyPressed
    int counter = 0;
    private void addClientBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addClientBtnMouseClicked
        // TODO add your handling code here:
        if (textMemo==null||textMemo.equals("")){
            client customer = new client(textFName, textLName, textAddress, textContact, textPest, textCost, "None");
            clientList.add(customer);
        } else {
            client customer = new client(textFName, textLName, textAddress, textContact, textPest, textCost, textMemo);
            clientList.add(customer);
        }
        for (int i=0; i<clientList.size(); i++){
            System.out.println(clientList.get(i));
        }
        File clientFile = new File("clients.txt");
        try {
            if (clientFile.exists()==false){
                clientFile.createNewFile();
            }
            PrintWriter clientPW = new PrintWriter(new FileWriter(clientFile, true));
            clientPW.append(clientList.get(counter) +  System.lineSeparator());
            counter++;
            clientPW.close();
        }
        catch(IOException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_addClientBtnMouseClicked
    private String textLName;
    private void addLastNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addLastNameFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            textLName = addLastNameField.getText();
        }
    }//GEN-LAST:event_addLastNameFieldKeyPressed

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        // TODO add your handling code here:
        DeleteScreen z = new DeleteScreen();
        z.setVisible(true);
    }//GEN-LAST:event_deleteBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addAddressField;
    private javax.swing.JButton addClientBtn;
    private javax.swing.JTextField addContactField;
    private javax.swing.JTextField addCostField;
    private javax.swing.JTextField addLastNameField;
    private javax.swing.JTextArea addMemoField;
    private javax.swing.JTextField addNameField;
    private javax.swing.JTextField addPestField;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAddAddress;
    private javax.swing.JLabel labelAddContact;
    private javax.swing.JLabel labelAddCost;
    private javax.swing.JLabel labelAddLastName;
    private javax.swing.JLabel labelAddMemo;
    private javax.swing.JLabel labelAddName;
    private javax.swing.JLabel labelAddPest;
    private javax.swing.JButton searchScreenBtn;
    private javax.swing.JButton tutorialBtn;
    // End of variables declaration//GEN-END:variables
}
